# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=500)),
                ('college_short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8)),
                ('course_offered_in', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=8)),
                ('course_title', models.CharField(max_length=100)),
                ('course_length', models.IntegerField()),
                ('course_units', models.IntegerField()),
                ('course_convenor', models.CharField(max_length=100)),
                ('course_convenor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('career', models.IntegerField()),
                ('delivery', models.IntegerField()),
                ('min_units', models.IntegerField()),
                ('convenor', models.CharField(max_length=100)),
                ('convenor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Spec_Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(max_length=10)),
                ('major_type', models.IntegerField()),
                ('major_title', models.CharField(max_length=200)),
                ('major_min_units', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bindi.Programs')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bindi.Programs'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bindi.Spec_Major'),
        ),
        migrations.AddField(
            model_name='course_offering',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bindi.Courses'),
        ),
    ]
